import { int, mysqlEnum, mysqlTable, text, timestamp, varchar, decimal, json } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", { id: int("id").autoincrement().primaryKey(), openId: varchar("openId", { length: 64 }).notNull().unique(), name: text("name"), email: varchar("email", { length: 320 }), loginMethod: varchar("loginMethod", { length: 64 }), role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull() });
export type User = typeof users.$inferSelect; export type InsertUser = typeof users.$inferInsert;

export const categories = mysqlTable("categories", { id: int("id").autoincrement().primaryKey(), name: varchar("name", { length: 120 }).notNull().unique(), slug: varchar("slug", { length: 140 }).notNull().unique(), description: text("description"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const products = mysqlTable("products", { id: int("id").autoincrement().primaryKey(), name: varchar("name", { length: 180 }).notNull(), slug: varchar("slug", { length: 200 }).notNull().unique(), description: text("description"), categoryId: int("categoryId"), price: decimal("price", { precision: 10, scale: 2 }).notNull(), salePrice: decimal("salePrice", { precision: 10, scale: 2 }), sku: varchar("sku", { length: 80 }), sizes: json("sizes"), stock: int("stock").default(0).notNull(), imageUrl: text("imageUrl"), status: mysqlEnum("status", ["draft", "active", "archived"]).default("active").notNull(), featured: int("featured").default(0).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const productImages = mysqlTable("productImages", { id: int("id").autoincrement().primaryKey(), productId: int("productId").notNull(), url: text("url").notNull(), sortOrder: int("sortOrder").default(0).notNull() });
export const orders = mysqlTable("orders", { id: int("id").autoincrement().primaryKey(), customerName: varchar("customerName", { length: 180 }).notNull(), phone: varchar("phone", { length: 40 }).notNull(), email: varchar("email", { length: 320 }), address: text("address").notNull(), city: varchar("city", { length: 120 }).notNull(), state: varchar("state", { length: 120 }).notNull(), pincode: varchar("pincode", { length: 20 }).notNull(), landmark: varchar("landmark", { length: 180 }), subtotal: decimal("subtotal", { precision: 10, scale: 2 }).notNull(), total: decimal("total", { precision: 10, scale: 2 }).notNull(), paymentStatus: mysqlEnum("paymentStatus", ["not_applicable", "pending"]).default("not_applicable").notNull(), status: mysqlEnum("status", ["pending", "confirmed", "processing", "shipped", "delivered", "cancelled"]).default("pending").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const orderItems = mysqlTable("orderItems", { id: int("id").autoincrement().primaryKey(), orderId: int("orderId").notNull(), productId: int("productId").notNull(), productName: varchar("productName", { length: 180 }).notNull(), size: varchar("size", { length: 30 }), quantity: int("quantity").notNull(), unitPrice: decimal("unitPrice", { precision: 10, scale: 2 }).notNull() });
export const orderStatusHistory = mysqlTable("orderStatusHistory", { id: int("id").autoincrement().primaryKey(), orderId: int("orderId").notNull(), status: varchar("status", { length: 40 }).notNull(), note: text("note"), createdAt: timestamp("createdAt").defaultNow().notNull() });
